services:
  backend:
    build:
      context: .
      dockerfile: activity-management-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/intervals_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - intervals-network
    restart: unless-stopped

  postgres:
    image: postgres:16-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: intervals_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d intervals_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - intervals-network

volumes:
  postgres_data:

networks:
  intervals-network:
    driver: bridge